### ISSUE TITLE
En el repositorio solo debe almacenarse código fuente

### ISSUE THREAD

**Issue by evolentini** [fcolavitte/TSSE-CESE#1]
En el repositorio no se debe almacenar ni código binario ni archivos generados por herramientas automáticas, solo se debe almacenar código fuente. Por eso la carpeta `TP2 - TDD/leds/build/` debe agregarse en el archivo `.gitignore` y eliminarse de repositorio. Ademas sería buena idea no utilizar espacios en los nombres de carpetas, por que por ejemplo te puede complicar definir el archivo `gitignore `.

@marianofino @rafaeloliva

**Comment by fcolavitte** [comment]
Perfecto, ya corregí los espacios en los nombres. Al realizar el push con los nuevos nombres las carpetas se duplicaron con nombres distintos por lo que luego de finalizar las correcciones de los issues las borraré. Lo comento ya que figurará también que se modificó el TP3 al realizar esta acción. Gracias.

**Comment by evolentini** [comment]
Esta corrección tambien aplica al TP3 que tambien tiene los binarios de las pruebas. Tambien debe incluirse la carpeta `TP3-testing_unitario/build` en el archivo `.gitignore`

@marianofino @rafaeloliva
